spring.application.name=expense-service
server.port=4001
spring.jpa.open-in-view=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/budget-portal}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8181/realms/budget-portal/protocol/openid-connect/certs}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}



spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name=expense-hikari
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

grpc.server.port=9001
budget.service.grpc.deadline-ms=${BUDGET_GRPC_DEADLINE_MS:1000}
logging.level.root=info



