spring.application.name=ai-service

server.port=4003
logging.level.root=info
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/budget-portal/protocol/openid-connect/certs}

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.representation.uuid=standard
