spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/budget-portal}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8181/realms/budget-portal/protocol/openid-connect/certs}
  jpa:
    open-in-view: false
server:
  port: 4000
